#App
spring.application.name=backend
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_pantry
spring.datasource.username=postgres
spring.datasource.password=julius9@SQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Server
server.port=8080
# Load local secrets (this file is gitignored)
spring.config.import=optional:classpath:application-local.properties